### ISSUE TITLE
how to run backend?

### ISSUE THREAD

**Issue by HYPER2208** [codersgyan/codershouse-mern#3]
There's a username issue after running node server.js command

**Comment by ghost** [comment]
C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\rest\Twilio.js:134
    throw new Error('username is required');
    ^

Error: username is required
    at new Twilio (C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\rest\Twilio.js:134:11)
    at initializer (C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\index.js:10:10)
    at Object.<anonymous> (C:\Users\yashg\WebRTC\codershouse-mern\backend\services\otp-service.js:9:33)

**Comment by ghost** [comment]
please help

**Comment by ghost** [comment]
backend error

**Comment by yashraj-exe** [comment]
> C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\rest\Twilio.js:134 throw new Error('username is required'); ^
> 
> Error: username is required at new Twilio (C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\rest\Twilio.js:134:11) at initializer (C:\Users\yashg\WebRTC\codershouse-mern\backend\node_modules\twilio\lib\index.js:10:10) at Object. (C:\Users\yashg\WebRTC\codershouse-mern\backend\services\otp-service.js:9:33)

Is your project runs ?
